version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_financial_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: financial_entity_db
    ports:
      - "3306:3306"
    restart: always

  app:
    build: .
    container_name: financial_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/financial_entity_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update